// Generated by CoffeeScript 1.7.1

/*
Created by massimo on 2014/4/12.
express-mvc framework
 */

(function() {
  var PROJECT_DIR, configRoute, cons, express, fs, path, resolveMethod, setOptions;

  fs = require("fs");

  express = require("express");

  path = require("path");

  cons = require("consolidate");

  PROJECT_DIR = path.join(__dirname, "../");


  /*
  配置路由
  @param options
  @param {String} [options.controllerPath="controller"] controller path
  @pram {String} [options.viewPath="views"] views path
  @param parentApp app
   */

  module.exports = function(options, parentApp) {
    var defaultFilterPath, filter;
    if (!parentApp) {
      parentApp = options;
      options = {};
    }
    setOptions(options, {
      controllerPath: "controllers",
      viewPath: "views"
    });
    if (!options.filter) {
      defaultFilterPath = path.join(PROJECT_DIR, "filter.js");
      if (fs.existsSync(defaultFilterPath)) {
        filter = require(defaultFilterPath);
      } else {
        filter = {};
      }
    }
    return fs.readdirSync(path.join(PROJECT_DIR, options.controllerPath)).forEach(function(fileName) {
      var $mvcConfig, app, controller, controllerName, engine, func, itemMethod, itemMiddleware, method, methodInfo, methodName, viewEngine, _i, _j, _len, _len1, _ref, _ref1, _ref2;
      if (fileName.slice(-3) === ".js") {
        controllerName = fileName.slice(0, -3);
        controller = require(path.join(PROJECT_DIR, options.controllerPath, controllerName));
        app = express();
        $mvcConfig = controller.$mvcConfig;
        if (options.viewPath) {
          engine = "swig";
          if (typeof $mvcConfig !== "undefined" && $mvcConfig.engine) {
            engine = $mvcConfig.engine;
          }
          viewEngine = (typeof $mvcConfig !== "undefined" && $mvcConfig.viewEngine ? $mvcConfig.viewEngine : void 0) || "html";
          app.engine("html", cons[engine]);
          app.set("view engine", viewEngine);
          app.set("views", path.join(PROJECT_DIR, options.viewPath, controllerName));
        }
        for (methodName in controller) {
          method = controller[methodName];
          if (methodName[0] === "$") {
            continue;
          }
          methodInfo = resolveMethod(methodName);
          setOptions(methodInfo, $mvcConfig != null ? (_ref = $mvcConfig.route) != null ? _ref[methodInfo.action] : void 0 : void 0, true);
          if (!methodInfo.path) {
            methodInfo.path = "/" + controllerName + "/" + methodInfo.action;
          }
          if (methodInfo.middleware) {
            _ref1 = methodInfo.middleware;
            for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
              itemMiddleware = _ref1[_i];
              func = controller[itemMiddleware] || filter[itemMiddleware];
              if (typeof func === "function") {
                if (controllerName === "home") {
                  configRoute(app, "all", "/", func);
                }
                if (methodInfo.action === "index") {
                  configRoute(app, "all", "/" + controllerName, func);
                }
                configRoute(app, "all", methodInfo.path, func);
              } else {
                throw new Error("can not find filter", itemMiddleware);
              }
            }
          }
          _ref2 = methodInfo.httpVerbs;
          for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
            itemMethod = _ref2[_j];
            if (controllerName === "home") {
              configRoute(app, itemMethod, "/", method);
            }
            if (methodInfo.action === "index") {
              configRoute(app, itemMethod, "/" + controllerName, method);
            }
            configRoute(app, itemMethod, methodInfo.path, method);
          }
        }
        return parentApp.use(app);
      }
    });
  };


  /*
  配置路由
  @param app application
  @param {String} method http request method
  @param {String} path route path
  @param {Function} func function
   */

  configRoute = function(app, method, path, func) {
    return app[method](path, func);
  };


  /*
  通过解析方法名获取方法支持的HTTP方法和中间件信息
  @param {String} methodName method name
   */

  resolveMethod = function(methodName) {
    var arr, httpVerbs, middleware;
    arr = methodName.split("_");
    httpVerbs = [];
    middleware = [];
    arr.slice(1).forEach(function(item) {
      if (item[0] === "$") {
        return middleware.push(item);
      } else {
        return httpVerbs.push(item.toLowerCase());
      }
    });
    if (httpVerbs.length <= 0) {
      httpVerbs.push("get");
    }
    return {
      action: arr[0],
      httpVerbs: httpVerbs,
      middleware: middleware
    };
  };


  /*
      set default options
      @param {Boolean} override override options by defaultOptions or not
   */

  setOptions = function(options, defaultOptions, override) {
    var key, value, _results;
    if (!defaultOptions) {
      return;
    }
    if (!options) {
      return options = defaultOptions;
    } else {
      _results = [];
      for (key in defaultOptions) {
        value = defaultOptions[key];
        if (override) {
          if (defaultOptions[key]) {
            _results.push(options[key] = value);
          } else {
            _results.push(void 0);
          }
        } else {
          if (!options[key]) {
            _results.push(options[key] = value);
          } else {
            _results.push(void 0);
          }
        }
      }
      return _results;
    }
  };

}).call(this);

//# sourceMappingURL=index.map
