// Generated by CoffeeScript 1.7.1
(function() {
  exports.bar = function(req, res) {
    return res.send(new Date());
  };

  exports.err = function(req, res) {
    throw new Error("test error");
  };

  exports.view = function(req, res) {
    return res.render("view", {
      title: "test view"
    });
  };

}).call(this);

//# sourceMappingURL=foo.map
